### ISSUE TITLE
[views][new_game] new_game method is huge! Let's modularize it

### ISSUE THREAD

**Issue by heyapricot** [zinagithub/my-tic-tac-toe#8]
The first thing you do is ask the player for a number between 0-9 or press q to quit. You could have a method that does this and only this
```
def get_player_input(player_number)
    puts "Player#{t} choose a number in 0 - #{dim * dim - 1}  or Q to quit!"
    cell = gets.chomp
    terminate if cell.upcase == 'Q'
end


def terminate
  p 'Quit'
  exit
end
```

**Comment by heyapricot** [comment]
Here is a suggestion for the new_game loop
```
def new_game(game)
    while true do
      input = get_player_input
      # In theory the next line will cycle until it gets a succesful write
      until game.board.change_mat(cell.to_i, game.turn)
      # If we reach this point we had a succesful write
      if game.has_winner
        print winner
      else
        print draw
      end
      switch_turn
end
```

**Comment by heyapricot** [comment]
Notice your loop has a lot of calls to `game`. That's a signal that the loop belongs to the `game` class, don't you think?

**Comment by zinagithub** [comment]
Hi Alvaro,
regarding modification of the method new_game because it is huge, in truth I do not agree but despite that I tried your version, I hardly found a solution for your version of the fact that yours does not correspond to what I wish (the method terminate exit all the programme i don't want that).
in the end I think I spent a lot of time programming this game I hope that this time you accept my work and switch to the testings review, also i want to tell you that i want to have with you a meeting if it is possible in order to give me more explanation.
thanks
